### create message
Post http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email" :"dj@gmail.com",
    "password" : "1234",
    "admin" : "True"
}

### get user 

GET http://localhost:3000/auth/12312421

### get users
GET http://localhost:3000/auth?email=bbbbbb@gmail.com


### Update user

PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
    "email":"bbbbbb@gmail.com"
}

### Delete user

DELETE http://localhost:3000/auth/12312412
